name: getfly_project
description: A new Flutter project.

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  intl: ^0.18.1
  localstorage: ^5.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/student.jpg